version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install
          with-cache: false
      # - run:
      #     command: npm run test
      #     name: Run tests
      - run:
          command: npm run build
          name: Build an App
      # - persist_to_workspace:
      #     root: ~/project
      #     paths:
      #       - .

workflows:
  build:
    jobs:
      - build_and_test
